version: "3.4"

services:
  backend:
    image: instigpt-backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: instigpt-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"
